databases-week3
Merhawi-gebreslasie/hyf-homework pull request #17
Opened 2022-02-16 08:13 UTC by Merhawi-gebreslasie

2022-02-20 15:20 UTC, martamatos requested changes
Good work overall Merhawi :)

Remember to leave empty lines between queries to make it easier to read.

And please make sure that all queries run without errors so i can test.

2022-02-20 15:20 UTC, martamatos commented on databases/week3/hyf_lesson3.sql
> +    `price` DECIMAL NOT NULL,
don't forget to specify how many digits you want in total and how many decimal places.

2022-02-20 15:20 UTC, martamatos commented on databases/week3/hyf_lesson3.sql
> +    contact_name ` VARCHAR(255) NOT NULL,
You're missing the opening ``` here.
Also, avoid the empty spaces in the column names.

2022-02-20 15:20 UTC, martamatos commented on databases/week3/hyf_lesson3.sql
> +    CONSTRAINT ` fk_meal ` FOREIGN KEY (` meal_id `) REFERENCES ` meal `(` id `) ON DELETE CASCADE
If we delete all reservations for a given meal, the meal entry will also be deleted, is that what you want? (It is ok, just checking ;) )
Also, what happens if you update the id of the meal?

2022-02-20 15:20 UTC, martamatos commented on databases/week3/hyf_lesson3.sql
> +        ` id `,
Remember, the `id`  is auto-incremened by MySQL, so you shouldn't insert it.

2022-02-20 15:20 UTC, martamatos commented on databases/week3/hyf_lesson3.sql
> +CREATE DATABASE hyf_lesson3;
When i try to run the code here i get a bunch of errors, please fix it so i can run it without problems :)

2022-02-20 15:20 UTC, martamatos commented on databases/week3/additional_meal_queries.sql
> +SELECT *
Having available reservations basically means that the sum of all guests for a given meal is less than max_reservations.

This is the trap query btw. You need to sum the number_of_guests over all reservations for a given meal and then compare that number with the max_reservations of that meal.

There are at least two ways of doing this, both involve stuff that we didnt talk about in class:
 - use the COALESCE() function: https://dev.mysql.com/doc/refman/8.0/en/comparison-operators.html#function_coalesce
 - use GROUP BY, SUM, and `HAVING: https://www.w3schools.com/sql/sql_having.asp

Also remember that there might be meals that don't have any reservations yet.

2022-02-20 15:20 UTC, martamatos commented on databases/week3/additional_meal_queries.sql
> +WHERE  revie.stars  > 4;
typo

2022-02-22 10:55 UTC, Merhawi-gebreslasie commented on databases/week3/additional_meal_queries.sql
> +WHERE  revie.stars  > 4;
Thanks Marta ,I have made the changes.

2022-03-06 10:36 UTC, merged